language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO=1.4.10
  - DJANGO=1.5.5
  - DJANGO=1.6.1
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -r requirements.txt --use-mirrors
matrix:
  exclude:
   - python: "3.2
     env: DJANGO=1.4.10
   - python: "3.3
     env: DJANGO=1.4.10
script: python manage.py test


