sudo: false
language: python

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - pypy

env:
  - DJANGO="django==1.9"
  - DJANGO="django==1.8.7"

install:
  - pip install $DJANGO
  - pip install -r requirements.txt
  - pip install -e .
  - pip install pep8
  - pip install https://github.com/un33k/pyflakes/tarball/master
  - pip install coveralls

before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225,E128 ."
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pyflakes -x W ipware; fi

matrix:
  exclude:
   - python: "3.3"
     env: DJANGO="django==1.9"

script: coverage run --source=ipware manage.py test

after_success:
  coveralls

