language: python

python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - pypy

env:
  - DJANGO="django==1.8"
  - DJANGO="django==1.7.7"
  - DJANGO="django==1.4.20"

install:
  - pip install $DJANGO
  - pip install -r requirements.txt
  - pip install -e .
  - pip install pep8
  - pip install https://github.com/un33k/pyflakes/tarball/master

before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225,E128 ."
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pyflakes -x W ipware; fi

matrix:
  exclude:
   - python: "3.4"
     env: DJANGO="django==1.4.20"
   - python: "3.3"
     env: DJANGO="django==1.4.20"
   - python: "3.2"
     env: DJANGO="django==1.4.20"
   - python: "2.6"
     env: DJANGO="django==1.7.7"
   - python: "2.6"
     env: DJANGO="django==1.8"

script: python manage.py test
